### ISSUE TITLE
invalid-function: log4e:deflogger

### ISSUE THREAD

**Issue by aaronjensen** [jwiegley/alert#93]
On Emacs 28/master I get:

```
Debugger entered--Lisp error: (invalid-function log4e:deflogger)
  log4e:deflogger("alert" "%t [%l] %m" "%H:%M:%S")
  alert-log-notify((:message "This is an alert" :title "*Messages*" :icon nil :severity normal :category nil :buffer #<buffer *Messages*> :mode messages-buffer-mode :id nil :data nil))
  alert("This is an alert")
  eval((alert "This is an alert") t)
  eval-expression((alert "This is an alert") nil nil 127)
  funcall-interactively(eval-expression (alert "This is an alert") nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

When I attempt to `M-: (alert "This is an alert")`

**Comment by iSeeU816** [comment]
@aaronjensen If you're using [Straight](https://github.com/raxod502/straight.el/tree/develop) as your Emacs package manager then
this has been fixed in [develop branch a few hours ago](https://github.com/raxod502/straight.el/commit/cd10de6895800802760d67d021e65da370c801f0).

I can't reproduce the bug with `package.el`.

Hope this helps.

**Comment by aaronjensen** [comment]
Thanks, I'll close this out.
